image: ubuntu:18.04

stages:
  - test
  - docker


test:
  stage: test
  script:
    - apt-get update -y
    - apt-get install -y golang
    - cd src
    - go test

docker:
  stage: docker
  tags:
    - shell

  script:
    - docker login registry.hal.davecutting.uk -u $username -p $password
    - docker build -t registry.hal.davecutting.uk/40173800/webcalc-multiply .
    - docker push registry.hal.davecutting.uk/40173800/webcalc-multiply
