image: ubuntu:18.04

stages:
    - docker
    
docker:
  stage: docker
  tags:
    - shell
  script:
    - docker login registry.hal.davecutting.uk -u $username -p $password
    - docker build -t registry.hal.davecutting.uk/40173800/webcalc-proxy .
    - docker push registry.hal.davecutting.uk/40173800/webcalc-proxy
