image: mcr.microsoft.com/dotnet/core/sdk:2.1

stages:
  - test
  #- docker

test:
  stage: test
  script:
    - dotnet test webcalc-modulo.sln

#docker:
 # stage: docker
  #tags:
   #- shell
  #script:
   #- docker login registry.hal.davecutting.uk -u $username -p $password
   #- docker build -t registry.hal.davecutting.uk/40173800/webcalc-modulo .
   #- docker push registry.hal.davecutting.uk/40173800/webcalc-modulo
